micronaut:
  application:
    name: smartpay-server
r2dbc:
  datasources:
    default:
      options:
        driver: pool
        protocol: postgres
        initialSize: 5
        maxSize: 35
        maxLifetime: PT280S
        maxIdleTime: PT240S
        maxAcquireTime: PT6S
        poolName: webcheckout-r2dbc
      schema-generate: CREATE_DROP
      dialect: POSTGRES
      db-type: postgres
      url: r2dbc:pool:postgresql://localhost:5432/smart_pay
      username: postgres
      password: sagar123

jwt:
  secret: cwuoye8uywc8736764bf797ey7928b7ey7by7y7937dbyyeguchdhatquwuuiuieupmj


